# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\x08\x64ocument\"4\n\x0e\x44ocumentChange\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\"\n\x10\x44ocumentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x12\x43hangeCheckRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"6\n\x0e\x44ocumentUpdate\x12\x13\n\x0bhas_changes\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\"\n\x0f\x44ocumentContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"%\n\x10SubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xa2\x02\n\x0f\x44ocumentService\x12\x44\n\x0cSyncDocument\x12\x18.document.DocumentChange\x1a\x1a.document.DocumentResponse\x12I\n\x0f\x43heckForChanges\x12\x1c.document.ChangeCheckRequest\x1a\x18.document.DocumentUpdate\x12\x39\n\x0bGetDocument\x12\x0f.document.Empty\x1a\x19.document.DocumentContent\x12\x43\n\tSubscribe\x12\x1a.document.SubscribeRequest\x1a\x18.document.DocumentChange0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTCHANGE']._serialized_start=28
  _globals['_DOCUMENTCHANGE']._serialized_end=80
  _globals['_DOCUMENTRESPONSE']._serialized_start=82
  _globals['_DOCUMENTRESPONSE']._serialized_end=116
  _globals['_CHANGECHECKREQUEST']._serialized_start=118
  _globals['_CHANGECHECKREQUEST']._serialized_end=157
  _globals['_DOCUMENTUPDATE']._serialized_start=159
  _globals['_DOCUMENTUPDATE']._serialized_end=213
  _globals['_DOCUMENTCONTENT']._serialized_start=215
  _globals['_DOCUMENTCONTENT']._serialized_end=249
  _globals['_SUBSCRIBEREQUEST']._serialized_start=251
  _globals['_SUBSCRIBEREQUEST']._serialized_end=288
  _globals['_EMPTY']._serialized_start=290
  _globals['_EMPTY']._serialized_end=297
  _globals['_DOCUMENTSERVICE']._serialized_start=300
  _globals['_DOCUMENTSERVICE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
